Repository eclipse-tractusx/portal-backend, pull requests merged in 2023-07, with the labels that each got.

#58 feat: removing CountryDe field
  src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/Administration.Service/Models/CompanyWithAddressData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/CompanyApplicationDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/RegistrationData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/registration/Registration.Service/Model/CompanyDetailData.cs
  src/registration/Registration.Service/Model/CompanyRegistrationData.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: breaking change

#91 feat(ssi): add submit endpoints
  src/administration/Administration.Service/Administration.Service.csproj
  src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/CompanyDataSettings.cs
  src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
  src/administration/Administration.Service/Controllers/CompanyDataController.cs
  src/administration/Administration.Service/DependencyInjection/CompanyDataServiceCollectionExtensions.cs
  src/administration/Administration.Service/Models/UseCaseParticipationCreationData.cs
  src/administration/Administration.Service/Program.cs
  src/administration/Administration.Service/appsettings.json
  src/framework/Framework.Linq/IfAnyExtension.cs
  src/framework/Framework.Models/Validation/EnumEnumerableValidation.cs
  src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
  src/portalbackend/PortalBackend.DBAccess/Extensions/MediaTypeIdExtensions.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanySsiDetailsRepository.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/CompanySsiDetail.cs
  src/processes/Processes.Worker/Program.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
  tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
  tests/administration/Administration.Service.Tests/appsettings.IntegrationTests.json
  tests/framework/Framework.Linq.Tests/IfAnyTests.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/verified_credential_type_assigned_use_cases.test.json
  tests/shared/Tests.Shared/Extensions/FakeIAsyncEnumerableExtensions.cs
Labels: priority

#125 chore: adjust roles for ssi endpoints
  src/administration/Administration.Service/Controllers/CompanyDataController.cs
  src/administration/Administration.Service/Models/UseCaseParticipationCreationData.cs
Labels: priority

#131 feat(daps): add config to disable daps calls
  src/administration/Administration.Service/BusinessLogic/ConnectorsBusinessLogic.cs
  src/administration/Administration.Service/Controllers/ConnectorsController.cs
  src/administration/Administration.Service/appsettings.json
  src/externalsystems/Daps.Library/DapsService.cs
  src/externalsystems/Daps.Library/DapsSettings.cs
  src/framework/Framework.Logging/LoggingExtensions.cs
  src/portalbackend/PortalBackend.DBAccess/Models/ConnectorData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ConnectorsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IConnectorsRepository.cs
  src/portalbackend/PortalBackend.Migrations/appsettings.json
  tests/externalsystems/Daps.Library.Tests/DapsServiceTests.cs
  tests/registration/ApplicationActivation.Library.Tests/ApplicationActivation.Library.Tests.csproj
Labels: priority

#142 chore: change LegalPerson to LegalParticipant for SD call
  src/externalsystems/SdFactory.Library/Models/SdFactoryRequestModel.cs
  src/externalsystems/SdFactory.Library/SdFactoryService.cs
Labels: priority

#121 feat(app)!: change app subscription process
  src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/Apps.Service/Controllers/AppsController.cs
  src/marketplace/Offers.Library/Service/OfferSubscriptionService.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferSubscriptionServiceTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Labels: merge postponed, breaking change, rel 1.6.0

#141 feat(serviceaccount):- get owncompany serviceaccounts
  src/portalbackend/PortalBackend.DBAccess/Models/CompanyServiceAccountData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
  src/portalbackend/PortalBackend.PortalEntities/Entities/CompanyServiceAccount.cs
  src/portalbackend/PortalBackend.PortalEntities/PortalDbContext.cs
  src/portalbackend/PortalBackend.PortalEntities/Views/CompaniesLinkedServiceAccount.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Labels: rel 1.6.0

#150 feat(ssi): enhance GET credentials endpoint
  src/administration/Administration.Service/BusinessLogic/CompanyDataBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/ICompanyDataBusinessLogic.cs
  src/administration/Administration.Service/Controllers/CompanyDataController.cs
  src/portalbackend/PortalBackend.DBAccess/Models/CredentialDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ICompanySsiDetailsRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/CompanyDataBusinessLogicTests.cs
  tests/administration/Administration.Service.Tests/Controllers/CompanyDataControllerTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
Labels: priority, rel 1.6.0

#153 feat(app): extend app provider endpoint with appInstanceId
  src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Labels: priority, rel 1.6.0

#154 feat(applicationChecklist)! : updated the createWallet responce message
  src/externalsystems/Custodian.Library/CustodianService.cs
  src/externalsystems/Custodian.Library/Models/WalletErrorResponse.cs
  tests/externalsystems/Custodian.Library.Tests/CustodianServiceTests.cs
Labels: rel 1.6.0

#163 feat(adminisration)! : added companyRole filed to ownCompanyDetails endpoint
  src/portalbackend/PortalBackend.DBAccess/Models/CompanyAddressDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
Labels: rel 1.6.0

#172 fix: resolved apps-business endpoint empty results
  src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/Apps.Service/Controllers/AppsController.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
Labels: priority, rel 1.6.0

#168 fix(ssi): ignore existing inactive ssi entries
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanySsiDetailsRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanySsiDetailsRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/company_ssi_details.test.json
Labels: rel 1.6.0

#158 fix(app): change appInstanceId to iamClientId for provider endpoint
  src/portalbackend/PortalBackend.DBAccess/Models/OfferSubscriptionDetailData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Labels: priority, rel 1.6.0

#157 chore: adjust logging for serilog
  src/administration/Administration.Service/appsettings.json
  src/marketplace/Apps.Service/appsettings.json
  src/marketplace/Services.Service/appsettings.json
  src/notifications/Notifications.Service/appsettings.json
  src/portalbackend/PortalBackend.Migrations/appsettings.json
  src/processes/Processes.Worker/appsettings.json
  src/provisioning/Provisioning.Migrations/appsettings.json
  src/registration/Registration.Service/appsettings.json
Labels: priority, rel 1.6.0

#164 feat(bpdm): adjust bpdm service calls to new service
  src/externalsystems/Bpdm.Library/Bpdm.Library.csproj
  src/externalsystems/Bpdm.Library/BpdmService.cs
  src/externalsystems/Bpdm.Library/BpnAccess.cs
  src/externalsystems/Bpdm.Library/DependencyInjection/BpdmServiceCollectionExtension.cs
  src/externalsystems/Bpdm.Library/DependencyInjection/BpnAccessCollectionExtension.cs
  src/externalsystems/Bpdm.Library/IBpnAccess.cs
  src/externalsystems/Bpdm.Library/Models/BpdmAddressDto.cs
  src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityData.cs
  src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityDto.cs
  src/externalsystems/Bpdm.Library/Models/BpdmLegalEntityOutputData.cs
  src/processes/ApplicationChecklist.Config/ApplicationChecklistExtensions.cs
  src/registration/Registration.Service/Bpn/BpnAccess.cs
  src/registration/Registration.Service/Bpn/Model/BpdmLegalEntityDto.cs
  src/registration/Registration.Service/Bpn/Model/FetchBusinessPartnerDto.cs
  src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/registration/Registration.Service/Controllers/RegistrationController.cs
  src/registration/Registration.Service/Program.cs
  tests/externalsystems/Bpdm.Library/BPNAccessTest.cs
  tests/externalsystems/Bpdm.Library/BpdmServiceTests.cs
  tests/registration/Registration.Service.Tests/BPNAccessTest.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/registration/Registration.Service.Tests/Controller/RegistrationControllerTest.cs
Labels: rel 1.6.0
