Repository eclipse-tractusx/portal-backend, pull requests merged in 2024-08, with the labels that each got.

#866 feat(osp): endpoint to get onboarding osp companies details
  src/administration/Administration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/administration/Administration.Service/Controllers/RegistrationController.cs
  src/administration/Administration.Service/Models/CompanyDetailsOspOnboarding.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ApplicationRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IApplicationRepository.cs
  src/portalbackend/PortalBackend.PortalEntities/Enums/CompanyApplicationStatusFilter.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
  tests/administration/Administration.Service.Tests/Controllers/RegistrationControllerTest.cs
Labels: priority

#877 fix(appRoles): don't allowed to upload duplicate app roles
  src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/AppChangeBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/Extensions/AppExtensions.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppChangeBusinessLogicTest.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
Labels: bug

#931 chore(TechnicalIntegrationCheckpoints): Correction of German translation
  src/portalbackend/PortalBackend.Migrations/Seeder/BatchUpdateSeeder.cs
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/user_role_descriptions.json
Labels: Task

#956 fix(technicalUser): adjust deletion process
  src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
  src/administration/Administration.Service/Controllers/IdentityProviderController.cs
  src/administration/Administration.Service/Controllers/ServiceAccountController.cs
  src/administration/Administration.Service/ErrorHandling/AdministrationServiceAccountErrorMessageContainer.cs
  src/portalbackend/PortalBackend.DBAccess/Models/OwnServiceAccountData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IServiceAccountRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ServiceAccountRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/ServiceAccountRespotitoryTests.cs
Labels: priority
