Repository eclipse-tractusx/portal-backend, pull requests merged in 2024-01, with the labels that each got.

#399 feat(conformity): enable conformity approval services
  src/portalbackend/PortalBackend.Migrations/Seeder/Data/agreements.json
Labels: priority

#321 fix(e2e): adjust end to end tests
  src/administration/Administration.Service/BusinessLogic/UserRolesBusinessLogic.cs
  src/portalbackend/PortalBackend.DBAccess/Models/ClearinghouseData.cs
  src/portalbackend/PortalBackend.DBAccess/Models/CompanyUserRoleWithId.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
  src/registration/Registration.Service/BusinessLogic/IRegistrationBusinessLogic.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/registration/Registration.Service/Controllers/RegistrationController.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
  tests/endtoend/InterfacePartnerHealthCheck/BpdmEndToEndTests.cs
  tests/endtoend/InterfacePartnerHealthCheck/SdFactoryEndPointTests.cs
  tests/endtoend/InterfacePartnerHealthCheck/WalletEndPointTests.cs
  tests/endtoend/NotificationInitScenario/ModifyCoreUserRoleScenario.cs
  tests/endtoend/PortalHealthCheck/BaseDataLoadCheck.cs
  tests/endtoend/PortalHealthCheck/RegistrationHealthCheck.cs
  tests/endtoend/RegistrationScenarios/BpdmContent.cs
  tests/endtoend/RegistrationScenarios/RegistrationEndpointHelper.cs
  tests/endtoend/RegistrationScenarios/RegistrationScenarios.cs
  tests/endtoend/ServiceAccountCUDScenarios/AdministrationEndpointHelper.cs
  tests/endtoend/ServiceAccountCUDScenarios/ServiceAccountCUDScenarios.cs
Labels: priority

#407 fix(registration): exclude inactive agreements
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
  src/registration/Registration.Service/Controllers/RegistrationController.cs
Labels: priority

#406 fix(registration): disable duplicate bpn check
  src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
  src/registration/Registration.Common/RegistrationValidation.cs
  src/registration/Registration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: priority

#410 fix(agreement): adjust GET: companyRoleAgreementConsents endpoint
  src/portalbackend/PortalBackend.DBAccess/Repositories/CompanyRolesRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/AgreementViewTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/CompanyRolesRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/NetworkRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/agreement_assigned_company_roles.test.json
Labels: priority

#409 feat(migrations): merge all migrations into one
  src/portalbackend/PortalBackend.Migrations/Migrations/20231128200842_CPLP-3451-CountryLongName.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20231128200842_CPLP-3451-CountryLongName.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20231214130927_CPLP-3523-UpdateCredentials.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20231214130927_CPLP-3523-UpdateCredentials.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20231214190249_CPLP-3091-remove-keycloak-identity-links.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20231214190249_CPLP-3091-remove-keycloak-identity-links.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20240102115525_CPLP-3469-AddAgreementView.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20240115113526_1.8.0-rc1.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20240115113526_1.8.0-rc1.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
Labels: priority

#417 fix(notifications): fix search-query resulting in 'Sequence contains more than one element'
  src/portalbackend/PortalBackend.DBAccess/Repositories/NotificationRepository.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/NotificationRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/Seeder/Data/notifications.test.json
Labels: bug

#423 fix(marketplace): set company policy for agreementConsents
  src/marketplace/Apps.Service/Controllers/AppReleaseProcessController.cs
  src/marketplace/Services.Service/Controllers/ServiceReleaseController.cs
Labels: priority

#459 fix(claims): change clientId claim to client_id
  src/framework/Framework.Models/PortalClaimTypes.cs
  tests/framework/Framework.Web.Tests/MandatoryIdentityClaimHandlerTests.cs
Labels: priority

#408 feat(searchpost): update pattern search same company name for post endpoint
  src/administration/Administration.Service/BusinessLogic/InvitationBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/NetworkBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/RegistrationBusinessLogic.cs
  src/framework/Framework.Models/ValidationExpressions.cs
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/InvitationBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
Labels: breaking change
