Repository eclipse-tractusx/portal-backend, pull requests merged in 2024-09, with the labels that each got.

#974 fix(subscriptionActivationEmail): null requester name
  src/mailing/Mailing.Template/EmailTemplates/serviceprovider_subscription_activation.html
Labels: bug

#969 feat(app): adjust status query param for subscription-status
  src/marketplace/Apps.Service/BusinessLogic/AppsBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/IAppsBusinessLogic.cs
  src/marketplace/Apps.Service/Controllers/AppsController.cs
  src/marketplace/Offers.Library/Service/IOfferService.cs
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/marketplace/Services.Service/BusinessLogic/IServiceBusinessLogic.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceBusinessLogic.cs
  src/marketplace/Services.Service/Controllers/ServicesController.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IOfferSubscriptionsRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/OfferSubscriptionsRepository.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/Controllers/AppsControllerTests.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceBusinessLogicTests.cs
  tests/marketplace/Services.Service.Tests/Controllers/ServiceControllerTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/OfferSubscriptionRepositoryTest.cs
Labels: priority

#982 feat(idp): add search functionallity to idp endpoint
  src/administration/Administration.Service/BusinessLogic/IIdentityProviderBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/IdentityProviderBusinessLogic.cs
  src/administration/Administration.Service/Controllers/IdentityProviderController.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IIdentityProviderRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IdentityProviderRepository.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/IdentityProviderBusinessLogicTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/IdentityProviderRepositoryTests.cs
Labels: priority

#990 fix(serviceAccount): return technical user in state pending deletion
  src/administration/Administration.Service/BusinessLogic/ServiceAccountBusinessLogic.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/ServiceAccountBusinessLogicTests.cs
Labels: bug, priority

#933 feat(invitation): allow access to invitation endpoint to technical user
  src/administration/Administration.Service/Controllers/InvitationController.cs
Labels: merge postponed

#922 fix(emailNotification): Add Multiple Users | Invite email didnt receive by User(s)
  src/administration/Administration.Service/BusinessLogic/UserBusinessLogic.cs
  src/administration/Administration.Service/BusinessLogic/UserUploadBusinessLogic.cs
  src/processes/Invitation.Executor/InvitationProcessService.cs
  src/provisioning/Provisioning.Library/Models/UserCreationRoleDataIdpInfo.cs
  src/provisioning/Provisioning.Library/Service/IUserProvisioningService.cs
  src/provisioning/Provisioning.Library/Service/UserProvisioningService.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserBusinessLogicTests.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/UserUploadBusinessLogicTests.cs
  tests/processes/Invitation.Executor.Tests/InvitationProcessServiceTests.cs
  tests/provisioning/Provisioning.Library.Tests/UserProvisioningServiceCreateUsersTests.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: bug
