Repository eclipse-tractusx/portal-backend, pull requests merged in 2025-02, with the labels that each got.

#1256 feat(technicalUser): enhance technical user profile with AccessiblyByProviderOnly flag
  docs/api/administration-service.yaml
  docs/api/apps-service.yaml
  docs/api/services-service.yaml
  src/administration/Administration.Service/BusinessLogic/ServiceAccountSettings.cs
  src/administration/Administration.Service/BusinessLogic/TechnicalUserBusinessLogic.cs
  src/administration/Administration.Service/Models/UserRoleWithDescription.cs
  src/administration/Administration.Service/appsettings.json
  src/framework/Framework.Async/Directory.Build.props
  src/framework/Framework.Cors/Directory.Build.props
  src/framework/Framework.DBAccess/Directory.Build.props
  src/framework/Framework.DBAccess/IQueryableExtensions.cs
  src/framework/Framework.DateTimeProvider/Directory.Build.props
  src/framework/Framework.DependencyInjection/Directory.Build.props
  src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
  src/framework/Framework.ErrorHandling.Web/Directory.Build.props
  src/framework/Framework.ErrorHandling/Directory.Build.props
  src/framework/Framework.HttpClientExtensions/Directory.Build.props
  src/framework/Framework.IO/Directory.Build.props
  src/framework/Framework.Identity/Directory.Build.props
  src/framework/Framework.Linq/Directory.Build.props
  src/framework/Framework.Logging/Directory.Build.props
  src/framework/Framework.Models/Directory.Build.props
  src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
  src/framework/Framework.Processes.Library/Directory.Build.props
  src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
  src/framework/Framework.Processes.Worker.Library/Directory.Build.props
  src/framework/Framework.Seeding/Directory.Build.props
  src/framework/Framework.Swagger/Directory.Build.props
  src/framework/Framework.Token/Directory.Build.props
  src/framework/Framework.Web/Directory.Build.props
  src/marketplace/Apps.Service/BusinessLogic/AppReleaseBusinessLogic.cs
  src/marketplace/Apps.Service/BusinessLogic/AppsSettings.cs
  src/marketplace/Apps.Service/appsettings.json
  src/marketplace/Offers.Library/ErrorHandling/OfferServiceErrorMessageContainer.cs
  src/marketplace/Offers.Library/Models/TechnicalUserProfileData.cs
  src/marketplace/Offers.Library/Service/IOfferService.cs
  src/marketplace/Offers.Library/Service/OfferService.cs
  src/marketplace/Services.Service/BusinessLogic/ServiceReleaseBusinessLogic.cs
  src/marketplace/Services.Service/ServiceSettings.cs
  src/marketplace/Services.Service/appsettings.json
  src/portalbackend/PortalBackend.DBAccess/Models/TechnicalUserProfileInformation.cs
  src/portalbackend/PortalBackend.DBAccess/Models/UserRoleData.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/ITechnicalUserProfileRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/IUserRolesRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/TechnicalUserProfileRepository.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/UserRolesRepository.cs
  src/provisioning/Provisioning.Library/Service/TechnicalUserCreation.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/TechnicalUserBusinessLogicTests.cs
  tests/marketplace/Apps.Service.Tests/BusinessLogic/AppReleaseBusinessLogicTest.cs
  tests/marketplace/Offers.Library.Tests/Service/OfferServiceTests.cs
  tests/marketplace/Services.Service.Tests/BusinessLogic/ServiceReleaseBusinessLogicTest.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/TechnicalUserProfileRepositoryTests.cs
  tests/portalbackend/PortalBackend.DBAccess.Tests/UserRolesRepositoryTests.cs
  tests/provisioning/Provisioning.Library.Tests/Extensions/TechnicalUserCreationTests.cs
Labels: Back-End

#1163 fix(osp): applied regex validation on uniqueIds param
  src/framework/Framework.Async/Directory.Build.props
  src/framework/Framework.Cors/Directory.Build.props
  src/framework/Framework.DBAccess/Directory.Build.props
  src/framework/Framework.DateTimeProvider/Directory.Build.props
  src/framework/Framework.DependencyInjection/Directory.Build.props
  src/framework/Framework.ErrorHandling.Controller/Directory.Build.props
  src/framework/Framework.ErrorHandling.Web/Directory.Build.props
  src/framework/Framework.ErrorHandling/Directory.Build.props
  src/framework/Framework.HttpClientExtensions/Directory.Build.props
  src/framework/Framework.IO/Directory.Build.props
  src/framework/Framework.Identity/Directory.Build.props
  src/framework/Framework.Linq/Directory.Build.props
  src/framework/Framework.Logging/Directory.Build.props
  src/framework/Framework.Models/Directory.Build.props
  src/framework/Framework.Models/ValidationExpressions.cs
  src/framework/Framework.Processes.Library.Concrete/Directory.Build.props
  src/framework/Framework.Processes.Library/Directory.Build.props
  src/framework/Framework.Processes.ProcessIdentity/Directory.Build.props
  src/framework/Framework.Processes.Worker.Library/Directory.Build.props
  src/framework/Framework.Seeding/Directory.Build.props
  src/framework/Framework.Swagger/Directory.Build.props
  src/framework/Framework.Token/Directory.Build.props
  src/framework/Framework.Web/Directory.Build.props
  src/registration/Registration.Common/RegistrationValidation.cs
  tests/administration/Administration.Service.Tests/BusinessLogic/NetworkBusinessLogicTests.cs
  tests/registration/Registration.Service.Tests/BusinessLogic/RegistrationBusinessLogicTest.cs
Labels: bug

#1265 chore(migrations): aggregate migrations for the release
  src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20241121163647_1140_Decline-Offer-Subscription.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250122160213_240-CreateProcessPackage.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250122160213_240-CreateProcessPackage.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250124063530_new_updated_provider_owned_usertype.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250124063530_new_updated_provider_owned_usertype.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250124140245_937_agreement-description.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250124140245_937_agreement-description.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250128164842_1111_CxMembership.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250128164842_1111_CxMembership.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250129171618_1180-SdSkippedDate.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250130083921_1211-AdjustCompanyLinkedTechnicalUsers.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250130083921_1211-AdjustCompanyLinkedTechnicalUsers.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250130122047_1182-AddNewProcesses.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250130122047_1182-AddNewProcesses.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250131094106_1244-RemoveDisplayTechnicalUser.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250131094106_1244-RemoveDisplayTechnicalUser.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250207083336_2.4.0-rc1.Designer.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/20250207083336_2.4.0-rc1.cs
  src/portalbackend/PortalBackend.Migrations/Migrations/PortalDbContextModelSnapshot.cs
Labels: pending migration

#1290 feat(connector): Integrate the Gaia-X Tagus Updates
  src/administration/Administration.Service/appsettings.json
  src/externalsystems/SdFactory.Library/Models/SdFactoryRequestModel.cs
  src/externalsystems/SdFactory.Library/SdFactoryService.cs
  src/externalsystems/SdFactory.Library/SdFactorySettings.cs
  src/processes/Processes.Worker/appsettings.json
  tests/externalsystems/SdFactory.Library.Tests/SdFactoryBusinessLogicTests.cs
  tests/externalsystems/SdFactory.Library.Tests/SdFactoryServiceTests.cs
Labels: Task

#1297 feat(sdFactory): selfdescription document anonymous allowed
  docs/api/administration-service.yaml
  src/administration/Administration.Service/Controllers/DocumentsController.cs
  src/portalbackend/PortalBackend.DBAccess/Repositories/DocumentRepository.cs
Labels: enhancement
